# Generated by Django 5.1.4 on 2024-12-24 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_alter_profiles_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='image',
        ),
        migrations.AddField(
            model_name='profiles',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
