# Generated by Django 5.1.4 on 2024-12-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_profiles_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='info',
            field=models.TextField(blank=True, default=True, max_length=512, null=True, verbose_name='Info'),
        ),
    ]
