# Generated by Django 5.1.4 on 2024-12-21 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id_question', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=512, verbose_name='Question')),
                ('number_of_passes', models.IntegerField(default=0, verbose_name='Numbder of passes')),
                ('number_of_correct_answers', models.IntegerField(default=0, verbose_name='Number of correct answers')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answer', to='quiz.question')),
            ],
        ),
    ]
